### ISSUE TITLE
Make task to deploy to server

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/new-salem-pelican#2]
Looks like there are already [a number of different tasks in the Makefile](https://github.com/scholarslab/new-salem-pelican/blob/master/Makefile#L104-L124) for deployment. We may need to modify this slightly, to allow for some local configuration file to be read, for authentication.

**Comment by shane-et-al** [comment]
Configured the ssh-upload and rsync-upload Make tasks and fixed the permissions on the static files in Git. Works for me; Jeremy should confirm that it's now working for him as well.

**Comment by jeremyboggs** [comment]
See if this can use the ssh/config.

**Comment by jeremyboggs** [comment]
Think this is done for now.
