### ISSUE TITLE
Missing Content: Record Books

### ISSUE THREAD

**Issue by rondauva** [scholarslab/new-salem-pelican#23]
Salem Village Church Joseph Green: http://salem.lib.virginia.edu/green.html

Parris’s successor was Rev Joseph Green who took over the keeping of the record book until his death. The text is a copy of a transcription published in The New England Historical and Genealogical Register, Vol, 11, 1857, (October) 321; Vol 12, (July) 1858; 127-128; (January) 245-248. [Transcribed by  Wm. Thaddeus Harris, Esq.]  This source information is missing and needs to be placed in a header page.

**Comment by shane-et-al** [comment]
Fixed 8319021c4efeb048675ea13a0196e5c22599bc72
