### ISSUE TITLE
Record Books: Erroneous Heading

### ISSUE THREAD

**Issue by rondauva** [scholarslab/new-salem-pelican#24]
First Church of Salem   The Record Book of the First Church of Salem is under copyright.  It contains relevant information about the SWT, and will likely be digitized by the Congregational Church Library under the directorship of James Cooper.

This is not a hyperlink but merely a heading for which there is no content, and it can be deleted.

**Comment by shane-et-al** [comment]
Fixed 8319021c4efeb048675ea13a0196e5c22599bc72
