### ISSUE TITLE
Press Archive Section: Link Requires Update

### ISSUE THREAD

**Issue by rondauva** [scholarslab/new-salem-pelican#28]
_“An Internet WITCH-HUNT Digitizing Salem Village A Conversation with Benjamin Ray” link is non-functional. Originally printed in the September/October 2000 issue of Humanities: The Magazine of the National Endowment for the Humanities.  
 	Above article MISSING LINK to important article about the site, its content and purpose. (from NEH)_

The contents at the link (http://salem.lib.virginia.edu/neh/NehSale.html) are in .lit Ebook format.

The article is on the NEH website at https://www.neh.gov/humanities/2000/septemberoctober/conversation/internet-witch-hunt

**Comment by shane-et-al** [comment]
The lit file link is broken on the old site too, of course. I'm going to assume that we can just kill it because Microsoft Reader hasn't been updated since 2007 and the latest operating system it officially supports is Vista.

**Comment by rondauva** [comment]
well, we should link to the article on the NEH site, but we don't have to keep the link with the .lit format stuff....

**Comment by shane-et-al** [comment]
Ah, yes, that is what I meant. Good, excellent. Fixed per 9092554834bcb2acc858efb21602ef1a569a7950
