### ISSUE TITLE
Press Archive Section: Salem Evening News Articles

### ISSUE THREAD

**Issue by rondauva** [scholarslab/new-salem-pelican#29]
Both articles linked under the Salem evening news are in .lit ebook format and will not render in modern browsers. (http://salem.lib.virginia.edu/salemnews.htm and http://salem.lib.virginia.edu/salempress99.html)

Article contents on the linked pages, if we can get rid of the ancient formatting. Live link unavailable from current newspaper website.

**Comment by shane-et-al** [comment]
Fixed 9092554834bcb2acc858efb21602ef1a569a7950
