### ISSUE TITLE
create documentation

### ISSUE THREAD

**Issue by rondauva** [scholarslab/new-salem-pelican#3]
Ben will need:

- [x] Markdown glossary/dictionary tailored to the Salem markup

- [x] Step-by-step workflow documentation for the entire process from document markup to upload.

- [x] SWP document template, as a starting place for any new case files he may need to add.

- [x] Example swp document, preferably as detailed as possible

**Comment by shane-et-al** [comment]
Lemme set up a docs directory here and start plunking down some basic stuff about Pelican and markdown.

**Comment by shane-et-al** [comment]
Took a first stab of documenting the SWP weirdness: https://github.com/scholarslab/new-salem-pelican/blob/master/docs/SWPdocs.md

**Comment by rondauva** [comment]
SWP template, markdown glossary, and annotated swp case file uploaded 9/3.

Workflow document needs a bit more discussion before I can write it.

**Comment by rondauva** [comment]
The docs are complete, until/if workflow changes for Ben.
