### ISSUE TITLE
Historical Works Section: The Witchcraft Delusion of 1692

### ISSUE THREAD

**Issue by rondauva** [scholarslab/new-salem-pelican#30]
from original site: http://salem.lib.virginia.edu/texts/tei/HutPool?div_id=d1e158
(404 error on http://newsalem.scholarslab.org/texts/tei/HutPool)

W. F. Poole’s name is missing on the Introduction and should be added.

Have emailed B. Ray for clarification.

**Comment by rondauva** [comment]
per Ben:

"W. F. Poole 'name should go by under the word "Introduction"  on the page"

**Comment by shane-et-al** [comment]
This is a 2-document Cocoon TEI that I missed because it was under the Historical Works page that is, for some reason, under the "Project Mission" header on the home page.

It's just two pages with no real formatting. Let's c/p it into a static html.

**Comment by shane-et-al** [comment]
I added the static page under the same URL (sorta). Kicking the styling to you, Jerm.

**Comment by shane-et-al** [comment]
https://github.com/scholarslab/new-salem-pelican/blob/master/static-salem/texts/tei/HutPool/index.html

**Comment by shane-et-al** [comment]
On newsalem: http://newsalem.scholarslab.org/texts/tei/HutPool/index.html
