### ISSUE TITLE
Selected Literary Works Section: Nathaniel Hawthorne Title's/Links To Be Removed

### ISSUE THREAD

**Issue by rondauva** [scholarslab/new-salem-pelican#32]
http://newsalem.scholarslab.org/texts/literary/index.html

under Hawthorne, Nathaniel remove links to 
"The Christmas Banquet." 
Endicott and the Red Cross 
Edward Fane's Rosebud 
John Inglefield's Thanksgiving

**Comment by shane-et-al** [comment]
Fixed c06758b4501c5d5132ec28dba934aa354cac97af
