### ISSUE TITLE
Selected Literary Works Section: Longfellow

### ISSUE THREAD

**Issue by rondauva** [scholarslab/new-salem-pelican#34]
Links to Longfellow play _Giles Corey of Salem Farms_ is currently linked to the internet archive.

Please update link to http://xtf.lib.virginia.edu/xtf/view?docId=legacy/uvaBook/tei/LonCore.xml

**Comment by shane-et-al** [comment]
We're actually linking to http://etext.lib.virginia.edu/toc/modeng/public/LonCore.html

It's etext.lib.virginia.edu that's 302 ("temporary") redirecting us to archive.org.

Will update with the new url.

**Comment by shane-et-al** [comment]
Fixed c06758b4501c5d5132ec28dba934aa354cac97af
