### ISSUE TITLE
Link Label Change: Diaries

### ISSUE THREAD

**Issue by rondauva** [scholarslab/new-salem-pelican#44]
Ben requests that the link text be changed from "Diaries" to

Diary of Samuel Sewall

He says that the link from this page to the actual diary contents is fine, but leaving it as is requires the user to click twice to get the contents. Shouldn't we just link to the final location of the diary text at http://newsalem.scholarslab.org/diaries/sewall_diary.html instead of an intermediate page?

**Comment by shane-et-al** [comment]
Fixed in 70732be29c44dabbfa9ad3fcb3c0e7cf8408fd8b and a75b12a957d4853b83b0f2421ac9921ecb6d3f34
