### ISSUE TITLE
Return index list of cases to search results

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/new-salem-pelican#57]
IN addition to displaying results by document, add the box to the left that lists the cases in which the search results belong.

**Comment by shane-et-al** [comment]
Corpus metadata for each doc now includes fields case_id and case_title. The title field now reflects the document title rather than case title.

**Comment by shane-et-al** [comment]
Seems to work just fine on local testing after ac7d10ab93a24e489ed7f9c20f7ccf83132e686b
